Repository eurofurence/reg-mail-service, pull requests merged in 2022-12, with the labels that each got.

#10 feat(#9): unify configuration and fully go to autumn logging
  docs/config.example.yaml
  internal/repository/config/config.go
  internal/repository/config/config_test.go
  internal/repository/config/loading.go
  internal/repository/config/loading_test.go
  internal/repository/config/structure.go
  internal/repository/config/validation.go
  internal/repository/database/init.go
  internal/repository/database/mysqldb/implementation.go
  internal/repository/logging/consolelogging/implementation.go
  internal/repository/logging/consolelogging/implementation_test.go
  internal/repository/logging/consolelogging/logformat/logformat.go
  internal/repository/logging/logger.go
  internal/web/controller/healthctl/healthctl.go
  internal/web/controller/mailctl/mailctl.go
  internal/web/util/validation/validationhelper.go
  internal/web/util/validation/validationhelper_test.go
Labels: documentation, enhancement

#11 Adds template validation (on creation/update)
  .github/workflows/codeql-analysis.yml
  docs/openapi.yaml
  internal/web/controller/mailctl/validation.go
  internal/web/controller/templatectl/templatectl.go
  internal/web/controller/templatectl/validation.go
Labels: bug, documentation, enhancement

#13 Adds more development related config options
  docs/config.example.yaml
  internal/repository/config/config.go
  internal/repository/config/structure.go
  internal/web/controller/mailctl/mailctl.go
Labels: documentation, enhancement

#16 GoMail implementation
  go.mod
  go.sum
  internal/repository/config/config.go
  internal/service/mailsrv/interfaces.go
  internal/service/mailsrv/mailsrv.go
  internal/web/controller/mailctl/mailctl.go
Labels: enhancement

#20 Optional mail auth (when password supplied)
  docs/config.example.yaml
  internal/service/mailsrv/mailsrv.go
Labels: documentation, enhancement
